# Generated by Django 4.2.5 on 2023-09-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(null=True, upload_to='course/', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(null=True, upload_to='lesson/', verbose_name='превью'),
        ),
    ]
