# Generated by Django 4.2.5 on 2023-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма оплаты'),
        ),
    ]
