# Generated by Django 4.2.5 on 2023-10-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма оплаты'),
        ),
    ]
