# Generated by Django 4.2.5 on 2023-11-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='amount',
        ),
    ]
