# Generated by Django 4.2.5 on 2023-10-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='id платежа на stripe'),
        ),
    ]
